all: al

al:
	gcc -o prog -g main.c stackElem.c stackArrayList.c
ll:
	gcc -o prog -g main.c stackElem.c stackLinkedList.c
sl:
	gcc -o prog -g main.c stackElem.c stackSinglyLinkedList.c
clean:
	rm -f prog

