all: counter

counter:
	gcc -o prog -g mapElem.c mapArrayList.c main.c 

linked:
	gcc -o prog -g mapElem.c mapLinkedList.c main.c

items:
	gcc -o prog -g item.c mapElem_items.c mapArrayList.c main_items.c 

clean:
	rm -f prog

